"""add author to notes

Revision ID: ce9376ff2c16
Revises: 
Create Date: 2026-04-27 11:29:28.494689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce9376ff2c16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('author', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'author')
    # ### end Alembic commands ###
