"""add ssh_command_prefix to user

Revision ID: d76457df98a4
Revises: ce9376ff2c16
Create Date: 2026-06-23 12:39:51.620054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd76457df98a4'
down_revision: Union[str, None] = 'ce9376ff2c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ssh_command_prefix', sa.String(length=64), server_default='ssh', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ssh_command_prefix')
    # ### end Alembic commands ###
